Tests fix
humanprotocol/cvat pull request #12
Opened 2021-08-31 17:12 UTC by Dzeranov

### Motivation and context

### How has this been tested?

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-09-07 12:07 UTC, vkomodey requested changes

2021-09-07 12:42 UTC, vkomodey requested changes

2021-09-07 12:42 UTC, vkomodey commented on tests/cypress/support/commands.js
> +    });
are you sure that this is working? the whole construction

`cy.request({}).then(() => {})` is asyncronus. But then you are doing `cy.visit(..)` which should wait for the `authKey` fulfillment. So I'm thinking that this `authKey` should be `undefined` at this moment

AND:

no need to create global var here. just push it to `then` pipeline:

```
cy.request({})
    .then(response => response['body']['key'])
    .then(token => cy.visit('/', {.. // expression with auth key}
```

2021-09-07 12:42 UTC, vkomodey commented on tests/cypress/support/commands.js
> +    });
or cypress requests are synchronous?

2021-09-07 12:42 UTC, vkomodey commented on tests/cypress/integration/actions_users/registration_involved/case_4_assign_taks_job_users.js
> +    }
DRY: 3 places with identical code. Move this to utils or smth

2021-09-07 12:42 UTC, vkomodey commented on tests/cypress/integration/actions_users/issue_1810_login_logout.js
> -            cy.closeNotification('.cvat-notification-notice-login-failed');
Here should be invalid credentials check. I assume in our case it should be existing user and not existing wallet address or vice versa

2021-09-09 10:43 UTC, Dzeranov commented on tests/cypress/integration/actions_tasks/registration_involved/case_39_issue_2572_rename_task.js
> +                Cypress.env('regularUserSignedEmail'),
Their first user was an admin. I decided to name a user as 'regularUser'. So no problems here.

2021-09-10 10:40 UTC, merged